spring:
  application:
    name: credit-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8090}/${DB_NAME:credit_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    topic:
      credit:
        name: credit-events


server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /api/v1

feign:
  clients:
    account:
      name: account-service
      url: http://localhost:8084

